version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: DemoUser
      MONGO_INITDB_ROOT_PASSWORD: demopassword
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
